# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=100, verbose_name='城市名')),
                ('confirmedCount', models.IntegerField(verbose_name='确诊病例数')),
                ('curedCount', models.IntegerField(verbose_name='治愈病例数')),
                ('deadCount', models.IntegerField(verbose_name='死亡病例数')),
                ('province_name', models.CharField(max_length=100, validators=['省', '份'])),
                ('date_info', models.CharField(max_length=100, validators=['日', '期'])),
                ('detail_time', models.CharField(max_length=100, validators=['详', '细', '时', '间'])),
                ('cycle', models.IntegerField(validators=['循', '环', '次', '数'])),
            ],
            options={
                'verbose_name_plural': '疫情数据',
                'db_table': 'data_all',
            },
        ),
    ]
